=== rybit/arinc_838/src/main/resources/ARINC838_Ver3.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- update carsten schweigert, 2011-02-13 -->
<!-- Update Timo NuÃŸbaumer, Vector Informatik GmbH (www.vector.com), 2011-10-27 -->
<!--<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.arinc.com/arinc838" 
	targetNamespace="http://www.arinc.com/arinc838"> -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.arinc.com/arinc838" xmlns:sdf="http://www.arinc.com/arinc838">
	<!--SIMPLE TYPE DEFINITIONS -->
	<xsd:annotation>
		<xsd:documentation>a</xsd:documentation>
	</xsd:annotation>
	<xsd:simpleType name="STR64K">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="65535" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="UINT32">
		<xsd:restriction base="xsd:unsignedInt" />
	</xsd:simpleType>

	<xsd:simpleType name="SOFTWARE-PARTNUMBER">
		<xsd:restriction base="xsd:string">
			<xsd:pattern
				value="[0-9A-Z]{3}[0-9A-F]{2}-[0-9A-HJ-NPR-Y]{4}-[0-9A-HJ-NPR-Y]{4}" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="FILENAME">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="255" />
			<!--<xsd:pattern value="[0-9a-zA-Z_-]+(\.[0-9a-zA-Z_-]+)?"/> -->
			<xsd:pattern
				value="[^&quot;\*&lt;\.&gt;\?\\\|~]+(\.[^&quot;\*&lt;\.&gt;\?\\\|~]+)?" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="INTEGRITY-TYPE">
		<xsd:restriction base="xsd:unsignedInt" />
	</xsd:simpleType>

	<xsd:simpleType name="INTEGRITY-VALUE">
		<xsd:restriction base="xsd:string" />
	</xsd:simpleType>

	<!--COMPLEX TYPE DEFINITIONS -->
	<xsd:complexType name="integrity-definition">
		<xsd:sequence>
			<xsd:element name="integrity-type" type="sdf:INTEGRITY-TYPE" />
			<xsd:element name="integrity-value" type="sdf:INTEGRITY-VALUE" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="thw-definition">
		<xsd:sequence>
			<xsd:element name="thw-id" type="sdf:STR64K"></xsd:element>
			<xsd:element minOccurs="0" maxOccurs="unbounded" name="thw-position"
				type="sdf:STR64K">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="file-definition">
		<xsd:sequence>
			<xsd:element name="file-loadable" type="xsd:boolean"></xsd:element>
			<xsd:element name="file-name" type="sdf:FILENAME"></xsd:element>
			<xsd:element name="file-size" type="sdf:UINT32"></xsd:element>
			<xsd:element name="file-integrity-definition" type="sdf:integrity-definition">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="sdf-sections">
		<xsd:sequence>
			<xsd:element name="software-description" type="sdf:software-description">
			</xsd:element>
			<xsd:element minOccurs="0" maxOccurs="unbounded" name="thw-definitions"
				type="sdf:thw-definition">
			</xsd:element>
			<xsd:element minOccurs="1" maxOccurs="unbounded" name="file-definitions"
				type="sdf:file-definition">
			</xsd:element>
			<xsd:element name="sdf-integrity-definition" type="sdf:integrity-definition">
			</xsd:element>
			<xsd:element name="lsp-integrity-definition" type="sdf:integrity-definition">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="software-description">
		<xsd:sequence>
			<xsd:element name="software-partnumber" type="sdf:SOFTWARE-PARTNUMBER">
			</xsd:element>
			<xsd:element name="software-type-description" type="sdf:STR64K"></xsd:element>
			<xsd:element name="software-type-id" type="sdf:UINT32"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<!--XML SCHEMA DEFINITION -->
	<xsd:element name="sdf-file">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="file-format-version" type="sdf:STR64K"></xsd:element>
				<xsd:element name="sdf-sections" type="sdf:sdf-sections">
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== rybit/arinc_838/src/test/resources/Sample_Ver3.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdf:sdf-file xmlns:sdf="http://www.arinc.com/arinc838"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.arinc.com/arinc838 ARINC838_Ver3.xsd ">
	<file-format-version>528384</file-format-version>
	<sdf-sections>
		<software-description>
			<software-partnumber>ACM-47-1234-5678</software-partnumber>
			<software-type-description>STD</software-type-description>
			<software-type-id>42</software-type-id>
		</software-description>
		<file-definitions>
			<file-loadable>true</file-loadable>
			<file-name>CRC_T05A.rom</file-name>
			<file-size>3976</file-size>
			<file-integrity-definition>
				<integrity-type>3</integrity-type>
				<integrity-value>0x96142DCA</integrity-value>
			</file-integrity-definition>
		</file-definitions>
		<file-definitions>
			<file-loadable>true</file-loadable>
			<file-name>CRC_T06A.rom</file-name>
			<file-size>18152</file-size>
			<file-integrity-definition>
				<integrity-type>3</integrity-type>
				<integrity-value>0xAE34897C</integrity-value>
			</file-integrity-definition>
		</file-definitions>
		<thw-definition>
			<thw-id>ID3</thw-id>
			<thw-position>R</thw-position>
			<thw-position>L</thw-position>
		</thw-definition>
		<sdf-integrity-definition>
			<integrity-type>3</integrity-type>
			<integrity-value>0x00000000</integrity-value>
		</sdf-integrity-definition>
		<lsp-integrity-definition>
			<integrity-type>3</integrity-type>
			<integrity-value>0x00000000</integrity-value>
		</lsp-integrity-definition>
	</sdf-sections>
</sdf:sdf-file>
